version: "3"

services:
  app:
    build:
    volumes:
    - .:app
    - /app/node_modules
    port:
      - 3000:3000
    env_file:
    - system.env

  database:
    image: "mariadb"
    env_file:
      - system.env